name:                sway-cycle-workspaces
version:             0.1.0.0
github:              "AndreiUlmeyda/sway-cycle-workspaces"
license:             "Unlicense"
author:              "Adrian Schurz"
maintainer:          "ulmeyda.smile@gmail.com"
copyright:           "2021 Adrian Schurz"

extra-source-files:
- README.md
- LICENSE

synopsis:            A tool to switch workspaces up or down on the currently focused monitor.
category:            Sway

description:         Please see the README on GitHub at <https://github.com/AndreiUlmeyda/sway-cycle-workspaces/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- turtle
- text

default-extensions:
  - OverloadedStrings
  - DerivingStrategies

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wmonomorphism-restriction
    - -Wimplicit-prelude
    - -Wmissing-local-signatures
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wpartial-fields
    - -Wall-missed-specialisations
    - -Wcpp-undef
    - -Wmissing-deriving-strategies
    - -Wunused-packages
    - -Wunused-type-patterns
    - -Wcompat
    - -Wsafe

executables:
  sway-cycle-workspaces:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sway-cycle-workspaces

tests:
  sway-cycle-workspaces-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sway-cycle-workspaces
    - hspec
    - QuickCheck
