name: build+tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Chechout repo
        uses: actions/checkout@v3
      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}
      - name: build and tests
        run: stack build --test
